// This file is auto-generated by the Convex CLI.
// When you run `npx convex dev`, Convex generates the typed wrappers for your functions.

export {
  mutationGeneric as mutation,
  queryGeneric as query,
  actionGeneric as action,
  internalMutationGeneric as internalMutation,
  internalQueryGeneric as internalQuery,
  internalActionGeneric as internalAction,
  httpActionGeneric as httpAction,
} from "convex/server";
